# Generated by Django 5.0 on 2023-12-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('email', models.TextField(max_length=30)),
                ('date_in', models.TextField(max_length=30)),
                ('date_out', models.TextField(max_length=30)),
                ('interest', models.IntegerField()),
                ('request', models.BooleanField()),
            ],
        ),
    ]
