# Generated by Django 5.0 on 2023-12-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='date_in',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='date_out',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
