# Generated by Django 5.0 on 2023-12-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_alter_productmodel_date_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='request',
            new_name='requested',
        ),
    ]
